{"trial_id": "0001", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "num_filters", "default": 4, "conditions": [], "values": [4, 8, 16], "ordered": true}}, {"class_name": "Choice", "config": {"name": "dense_activation", "default": "relu", "conditions": [], "values": ["relu", "selu", "tanh", "sigmoid"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "kernel_size", "default": 4, "conditions": [], "values": [3, 4, 5], "ordered": true}}, {"class_name": "Choice", "config": {"name": "window_size", "default": 4, "conditions": [], "values": [3, 4, 5], "ordered": true}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}], "values": {"num_filters": 8, "dense_activation": "relu", "kernel_size": 4, "window_size": 3, "learning_rate": 0.001, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 1, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/alexandremonod/Python/OC_ML/projet_6_classer_des_images/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/alexandremonod/Python/OC_ML/projet_6_classer_des_images/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/alexandremonod/Python/OC_ML/projet_6_classer_des_images/.venv/lib/python3.10/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/alexandremonod/Python/OC_ML/projet_6_classer_des_images/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/Users/alexandremonod/Python/OC_ML/projet_6_classer_des_images/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/Users/alexandremonod/Python/OC_ML/projet_6_classer_des_images/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/Users/alexandremonod/Python/OC_ML/projet_6_classer_des_images/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/var/folders/z3/8962l16x2hbb_4qm7s2df7gc0000gn/T/__autograph_generated_filekgldnbqo.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"/Users/alexandremonod/Python/OC_ML/projet_6_classer_des_images/.venv/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1338, in train_function  *\n        return step_function(self, iterator)\n    File \"/Users/alexandremonod/Python/OC_ML/projet_6_classer_des_images/.venv/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1322, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/alexandremonod/Python/OC_ML/projet_6_classer_des_images/.venv/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1303, in run_step  **\n        outputs = model.train_step(data)\n    File \"/Users/alexandremonod/Python/OC_ML/projet_6_classer_des_images/.venv/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1080, in train_step\n        y_pred = self(x, training=True)\n    File \"/Users/alexandremonod/Python/OC_ML/projet_6_classer_des_images/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"/Users/alexandremonod/Python/OC_ML/projet_6_classer_des_images/.venv/lib/python3.10/site-packages/keras/src/engine/input_spec.py\", line 298, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential\" is incompatible with the layer: expected shape=(None, 300, 300, 3), found shape=(None, 224, 224, 3)\n\n"}